name: dio_rock
description: A powerful Http client for Dart, which supports Interceptors, FormData, Request Cancellation, File Downloading, Timeout etc.
version: 0.0.1
homepage: https://github.com/flutterchina/dio
author: wendux <824783146@qq.com>
environment:
  sdk: '>2.2.9 <3.0.0'

dependencies:
  dio:
    path: dio
  test: ^1.5.0
  test_coverage: ^0.2.0



